version: '3'

services:
  theia:
    image: "theia-plantuml"
    container_name: theia-plantuml
    ports:
      - "3030:3000"
    volumes:
      - ./settings.json.template:/root/.theia/settings.json.template:ro
      - ../workspace:/home/project:cached
    env_file:
      - ../.etc/domain.env

  plantuml:
    image: "plantuml/plantuml-server"
    container_name: plantuml-server
    environment:
      - PLANTUML_LIMIT_SIZE=40960
    ports:
      - "18080:8080"

